// ---------------------------------------------------------------------------------------------
// Application Main Entry Point (e.g., main.rs)
// --------------------------------------------------------------------------------------------
// This file serves as the primary entry point for the Tauri application.
// Its current responsibilities include:
//
// 1. **Logger Initialization (Debug Builds Only):**
//     - If compiled in debug mode (`debug_assertions`), it initializes
//       `env_logger`.
//     - The logger is configured with a specific format that includes a
//       "Mountain" prefix (colored red) and color-coded log levels (ERROR,
//       WARN, INFO, DEBUG, TRACE).
//
// 2. **Tokio Runtime Setup:**
//     - It creates a new multi-threaded Tokio runtime with all features
//       enabled.
//     - The entire application logic, including the Tauri setup and run loop,
//       is executed within this Tokio runtime's `block_on` context.
//
// 3. **Tauri Application Setup:**
//     - Initializes a default Tauri application builder
//       (`tauri::Builder::default()`).
//     - Conditionally enables `any_thread` for the builder on Windows and
//       Linux, which might be related to specific threading requirements or
//       plugin compatibility on those platforms.
//
// 4. **Main Window Creation (within `.setup()` hook):**
//     - Uses `tauri::WebviewWindowBuilder` to construct the main application
//       window.
//     - The window is named "Application" internally by Tauri.
//     - It loads its content from `Application/index.html` within the Tauri
//       application's bundled assets, using the `app://` scheme (via
//       `tauri::WebviewUrl::App`).
//     - Configures the webview to use an HTTPS scheme internally
//       (`use_https_scheme(true)`). This is often for security reasons or to
//       enable certain web APIs.
//     - Enables zoom hotkeys.
//     - Disables browser extensions within the webview.
//     - **Platform-Specific Window Customization:**
//       - On Windows, macOS, and Linux:
//         - Sets the window title to "FIDDEE".
//         - Starts the window maximized.
//         - Disables default window decorations (title bar, min/max/close
//           buttons), implying a custom title bar might be implemented in the
//           frontend.
//         - Enables window shadow.
//     - **Error Handling:** If window creation fails, it logs the error and
//       panics.
//     - **Developer Tools (Debug Builds Only, Desktop Only):**
//       - If compiled in debug mode and not on Android or iOS, it automatically
//         opens the webview's developer tools.
//
// 5. **Tauri Application Execution:**
//     - Runs the configured Tauri application using `Builder.run()`, providing
//       the context generated by `tauri::generate_context!()` (which typically
//       loads `tauri.conf.json`).
//     - Panics if the Tauri application fails to run.
//
// **Current Scope and Limitations:**
// - This file focuses solely on initializing the logger (debug only), Tokio
//   runtime, and setting up and running a basic Tauri application with a single
//   main window.
// - It does not include the more advanced backend logic, state management
//   (`AppState`), effect system (`AppRuntime`), sidecar process management
//   (Cocoon), IPC (Vine), or detailed command/RPC dispatching that were
//   discussed and documented for the broader "Mountain" backend system.
// - The "Mountain" prefix in the logger is present, but the extensive Mountain
//   functionality isn't yet integrated into this specific main entry point.
// - The window title "FIDDEE" suggests this might be a specific application
//   variant or project name, distinct from a generic "Mountain" or "Land
//   Editor" placeholder.
//
// This setup provides a foundation for a Tauri application, upon which the more
// complex backend services and logic (like the "Mountain" system) would be
// built and integrated, typically within the `.setup()` hook or through Tauri
// commands and state management.
// ---------------------------------------------------------------------------------------------

// Allows non_snake_case identifiers like `Buffer`, `Record`, `Builder`,
// `Tauri`, `Window`, `BuildError`
#![allow(non_snake_case)]

// Allows the `Fn` function to be unused if this is part of a library or not the
// final main
#[allow(dead_code)]
pub fn Fn() {
	// --- Logger Initialization (Debug Builds Only) ---
	// This block is only compiled in debug mode
	#[cfg(debug_assertions)]
	{
		// Attempt to initialize env_logger for colored and formatted logging.
		env_logger::Builder::new()
			// Set the default filter level to Debug. This can be overridden by RUST_LOG environment variable.
			.filter_level(log::LevelFilter::Debug)
			// Define a custom log format.
			.format(|Buffer, Record| {
				// Buffer is a `&mut env_logger::fmt::Formatter` which implements `std::io::Write`.
				// Record is a `&log::Record`.
				// Import Write trait for Buffer.write_fmt
				use std::io::Write;

				// For coloring log output
				use colored::Colorize;

				// Write the formatted log line to the buffer.
				writeln!(
					Buffer,
					// Log format: [AppPrefix] [LEVEL]: Message
					"[{}] [{}]: {}",
					// Application prefix, colored red.
					"Mountain".red(),
					match Record.level() {
						// Color-code log levels for better readability.
						log::Level::Error => "ERROR".red(),
						log::Level::Warn => "WARN".yellow(),
						log::Level::Info => "INFO".green(),
						log::Level::Debug => "DEBUG".blue(),
						log::Level::Trace => "TRACE".magenta(),
					},
					// The actual log message.
					Record.args()
				)
			})
			// Attempt to initialize the logger.
			.try_init()
			// `try_init` is used because a logger might have already been set globally.
			.expect("Failed to initialize env_logger. Another logger might be active, or an internal error occurred.");
	}

	// --- Tokio Runtime Setup and Application Execution ---
	// Create a new multi-threaded Tokio runtime.
	tokio::runtime::Builder::new_multi_thread()
		// Enable all Tokio features (I/O, time, etc.).
		.enable_all()
		// Build the runtime.
		.build()
		.expect("Failed to build Tokio runtime. This is a critical failure.")
		// Block the current thread on the execution of the async block.
		// The entire Tauri application lifecycle will run within this Tokio runtime.
		.block_on(async {
			// --- Tauri Application Builder Initialization ---
			// Start with a default Tauri application builder.
			let mut Builder = tauri::Builder::default();

			// Conditionally enable `any_thread` for the Tauri builder on Windows and Linux.
			// This allows Tauri event handlers and commands to run on any thread,
			// which might be necessary for certain plugins or async operations that don't
			// strictly adhere to the main thread for UI updates (though direct UI updates
			// should still be on the main thread).
			#[cfg(any(windows, target_os = "linux"))]
			{
				Builder = Builder.any_thread();
			}

			// --- Tauri Application Setup and Main Window Creation ---
			Builder
				// The `.setup()` hook runs after WebView2 is ready, before window creation.
				.setup(|Tauri| {
					// `Tauri` here is an `&mut tauri::App`.

					// --- Main Window Configuration ---
					let mut Builder = tauri::WebviewWindowBuilder::new(
						// The App instance.
						Tauri,
						// Internal label for the window. Can be used to get a handle to it later.
						"Application",
						// URL to load in the webview. `App` variant loads from bundled assets.
						tauri::WebviewUrl::App(std::path::PathBuf::from("Application/index.html")),
					)
					// Force the webview to use an internal HTTPS scheme (e.g., `https://tauri.localhost`).
					// This can enable certain web APIs that require a secure context.
					.use_https_scheme(true)
					// If enabled, would attempt to protect webview content (platform-dependent).
					// .content_protected(true)
					// Allow standard browser zoom hotkeys (Ctrl+Plus, Ctrl+Minus, Ctrl+0).
					.zoom_hotkeys_enabled(true)
					// Disable browser extension loading in the webview.
					.browser_extensions_enabled(false);

					// Platform-specific window styling (title, maximization, decorations).
					#[cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))]
					{
						Builder = Builder
							// Set the window title.
							.title("FIDDEE")
							// Start the window maximized.
							.maximized(true)
							// Remove default OS window decorations (title bar, buttons).
							.decorations(false)
							// This implies a custom title bar will be implemented in the frontend.
							// Enable window shadow (platform-dependent).
							.shadow(true);
					}

					// Build the main window.
					// `Window` might be unused if only devtools are opened.
					#[allow(unused_variables)]
					let Window = match Builder.build() {
						// Successfully created the window instance.
						Ok(Instance) => Instance,
						Err(BuildError) => {
							// Window creation failed. This is critical.
							log::error!("Main application window build failed: {:?}", BuildError);

							// Panic to halt execution as the main UI cannot be displayed.
							panic!("Main application window build failed: {:?}", BuildError);
						}
					};

					// --- Developer Tools (Debug Builds, Desktop Platforms Only) ---
					#[cfg(all(
						// Only in debug builds.
						debug_assertions,
						// Not for mobile platforms.
						not(any(target_os = "android", target_os = "ios"))
					))]
					{
						// Open the webview's developer tools.
						Window.open_devtools();

						// Example: could also close them if needed.
						// Window.close_devtools();
					}

					// Indicate successful setup.
					Ok(())
				})

				.plugin(tauri_plugin_dialog::init())

				// Run the Tauri application. This starts the event loop.
				// `tauri::generate_context!()` loads configuration from `tauri.conf.json` and embed assets.
				.run(tauri::generate_context!())
				.expect("Error while running Tauri application. This is a critical failure.");
		});
}
