[[bin]]
name = "Mountain"
path = "Source/Library.rs"

[build-dependencies]
json5 = { workspace = true }
toml_edit = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri-build = { workspace = true, features = [] }
toml = { workspace = true }

[dependencies]
tauri = { version = "*", features = [
	"wry",
	"tray-icon",
	"devtools",
	"rustls-tls",
	"compression",
], default-features = false }

tauri-plugin-dialog = { workspace = true }

async-trait = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
colored = { workspace = true }
Common = { workspace = true }
dirs = { workspace = true }
Echo = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true, features = ["sink", "std"] }
globset = { workspace = true }
ignore = { workspace = true }
keyring = { workspace = true }
log = { workspace = true }
md5 = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }
toml = { workspace = true }
tonic = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
parking_lot = { workspace = true }
lazy_static = { workspace = true }
portable-pty = { workspace = true }

# regex = { workspace = true }
# unbug = { workspace = true }

[features]
default = ["extension_host_cocoon", "mist_native"]

extension_host_cocoon = []

mist_native = []

Debug = []

[lib]
name = "Mountain"
path = "Source/Library.rs"
crate-type = ["lib"]

[package]
authors = ["Source 🖋️ Open 👐🏻 <Source/Open@Editor.Land>"]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Mountain"
description = "Mountain ⛰️"
edition = "2024"
license-file = "LICENSE"
name = "Mountain"
publish = false
version = "0.0.1"
