[[bin]]
name = "Mountain"
path = "Source/Library.rs"

[build-dependencies]
json5 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri-build = { version = "2.1.1", features = [] }
toml = { workspace = true }

[dependencies]
async-trait = { workspace = true }
colored = "3.0.0"
Echo = { workspace = true }
env_logger = "0.11.8"
futures = { workspace = true }
log = "0.4.27"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2.5.1", features = [
	"wry",
	"tray-icon",
	"devtools",
	"rustls-tls",
	"compression",
], default-features = false, git = "https://github.com/tauri-apps/tauri", branch = "feat/mobile-dev-cert" }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
unbug = { workspace = true }
base64 = "0.22.1"

[features]
Debug = []
default = []

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "Mountain"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Mountain"
description = "Mountain ⛰️"
edition = "2024"
license-file = "LICENSE"
name = "Mountain"
publish = false
version = "0.0.1"
