//! # Environment
//!
//! Dependency injection container that provides thread-safe access to
//! all Mountain providers through trait-based lookups via the `Requires` trait.
//!
//! ```text
//! Component -> Requires<T> -> MountainEnvironment -> Arc<dyn T>
//! ```
//!
//! `MountainEnvironment` implements the `Environment` and `Requires` traits
//! from the Common crate. It is constructed once during startup and shared
//! as `Arc<MountainEnvironment>` across all subsystems. Provider trait
//! implementations are generated by `ProviderTraitImplMacro` to keep
//! boilerplate minimal.
//!
//! ## Provider Traits Implemented
//!
//! `CommandExecutor`, `ConfigurationProvider`, `CustomEditorProvider`,
//! `DebugService`, `DiagnosticManager`, `DocumentProvider`,
//! `FileSystemReader`/`Writer`, `FileWatcher`, `IPCProvider`,
//! `KeybindingProvider`, `LanguageFeatureProviderRegistry`,
//! `OutputChannelManager`, `SearchProvider`, `SecretProvider`,
//! `SourceControlManagementProvider`, `StatusBarProvider`, `StorageProvider`,
//! `SynchronizationProvider`, `TerminalProvider`, `TestController`,
//! `TreeViewProvider`, `UserInterfaceProvider`, `WebviewProvider`,
//! `WorkspaceProvider`, `WorkspaceEditApplier`, `ExtensionManagementService`.
//!
//! Providers use `CommonError` for error reporting. Trait resolution is
//! compile-time, ensuring type safety with zero runtime overhead.

/// Main dependency injection container struct implementing all provider traits.
pub mod MountainEnvironment;

/// Declarative macro that generates `Requires<dyn T>` impl blocks
/// for each provider trait on `MountainEnvironment`. Invoked as
/// `impl_provider!(CommandExecutor)` from the parent file.
pub mod ProviderTraitImplMacro;

/// `CommandExecutor` provider: runs shell commands in a managed subprocess.
pub mod CommandProvider;

/// `ConfigurationProvider`: reads, writes, and watches workspace configuration.
pub mod ConfigurationProvider;

/// `CustomEditorProvider`: registers and resolves custom editor contributions.
pub mod CustomEditorProvider;

/// `DebugService`: manages debug adapter protocol sessions.
pub mod DebugProvider;

/// `DiagnosticManager`: collects and publishes editor diagnostic markers.
pub mod DiagnosticProvider;

/// `DocumentProvider`: opens, closes, and tracks text document state.
pub mod DocumentProvider;

/// `FileSystemReader`/`Writer`: async file-system read and write operations.
pub mod FileSystemProvider;

/// `FileWatcher`: registers file-system watch patterns and delivers change
/// events.
pub mod FileWatcherProvider;

/// Server-side path ignore filter applied before file-watcher events
/// cross the Mountain→Cocoon IPC boundary.
pub mod FileWatcherIgnore;

/// `IPCProvider`: routes IPC messages between the frontend and backend.
pub mod IPCProvider;

/// `KeybindingProvider`: resolves keybinding contributions and chord sequences.
pub mod KeybindingProvider;

/// `LanguageFeatureProviderRegistry`: dispatches LSP-like language features.
pub mod LanguageFeatureProvider;

/// `OutputChannelManager`: creates and writes to named output channels.
pub mod OutputProvider;

/// `SearchProvider`: runs workspace-wide text and symbol searches.
pub mod SearchProvider;

/// `SecretProvider`: reads and writes secrets from the platform credential
/// store.
pub mod SecretProvider;

/// `SourceControlManagementProvider`: exposes SCM repository state and actions.
pub mod SourceControlManagementProvider;

/// `StatusBarProvider`: creates and updates status bar items.
pub mod StatusBarProvider;

/// `StorageProvider`: persists extension and workspace state blobs.
pub mod StorageProvider;

/// `SynchronizationProvider`: coordinates cross-window state synchronization.
pub mod SynchronizationProvider;

/// `TerminalProvider`: creates and manages integrated terminal instances.
pub mod TerminalProvider;

/// `TestController`: registers test run profiles and reports test results.
pub mod TestProvider;

/// `TreeViewProvider`: supplies data for tree-view panel contributions.
pub mod TreeViewProvider;

/// `UserInterfaceProvider`: drives quick-pick, input-box, and notification UI.
pub mod UserInterfaceProvider;

/// `WebviewProvider`: creates and manages sandboxed webview panels.
pub mod WebviewProvider;

/// `WorkspaceProvider`: exposes workspace folders, trust state, and edits.
pub mod WorkspaceProvider;

/// Shared helpers used across multiple provider implementations.
pub mod Utility;
