//! # Vine Generated Code
//!
//! This module includes and re-exports the Rust code that is automatically
//! generated by `tonic-build` from the `Vine.proto` definition file. It serves
//! as the single source of truth for all gRPC message types, service traits,
//! and client/server structs. Do not edit this file directly.

#![allow(non_snake_case, non_camel_case_types, clippy::all, unused_imports, unknown_lints)]

// The `tonic::include_proto!` macro finds the file generated by `tonic-build`
// in the `OUT_DIR` and includes its contents here.
tonic::include_proto!("vine_ipc");

// Re-export all generated types to make them directly accessible under the
// `Generated` module.
pub use vine_ipc::*;
