//! Single-entry dispatch for all Cocoon → Mountain gRPC notifications.

use serde_json::Value;

use crate::Vine::Server::MountainVinegRPCService::MountainVinegRPCService;
use super::{
	ApplyTextEdits,
	DebugLifecycle,
	DecorationTypeLifecycle,
	DisposeStatusBarItem,
	ExtensionActivated,
	ExtensionDeactivated,
	ExtensionHostMessage,
	LanguagesSetDocumentLanguage,
	OpenExternal,
	OutputAppend,
	OutputAppendLine,
	OutputChannelAppend,
	OutputChannelClear,
	OutputChannelCreate,
	OutputChannelDispose,
	OutputChannelHide,
	OutputChannelShow,
	OutputClear,
	TerminalLifecycle,
	UnregisterAuthenticationProvider,
	UnregisterCommand,
	UnregisterDebugAdapter,
	UnregisterDebugConfigurationProvider,
	UnregisterExternalUriOpener,
	UnregisterFileSystemProvider,
	UnregisterRemoteAuthorityResolver,
	UnregisterScmProvider,
	UnregisterTaskProvider,
	UnregisterUriHandler,
	UpdateScmGroup,
	WebviewDispose,
	WebviewLifecycle,
	WebviewPostMessage,
	WebviewReady,
	WindowCreateTerminal,
	WindowShowMessage,
	WindowShowTextDocument,
	WorkspaceApplyEdit,
};

pub async fn Fn(Service:&MountainVinegRPCService, MethodName:&str, Parameter:&Value) {
	match MethodName {
		"extensionHostMessage" => ExtensionHostMessage::Fn(Service, Parameter).await,
		"ExtensionActivated" => ExtensionActivated::Fn(Service, Parameter).await,
		"ExtensionDeactivated" => ExtensionDeactivated::Fn(Service, Parameter).await,
		"WebviewReady" => WebviewReady::Fn(Service, Parameter).await,
		"workspace.applyEdit" => WorkspaceApplyEdit::Fn(Service, Parameter).await,
		"window.showTextDocument" => WindowShowTextDocument::Fn(Service, Parameter).await,
		"window.createTerminal" => WindowCreateTerminal::Fn(Service, Parameter).await,
		"window.setTextEditorDecorations" => DecorationTypeLifecycle::Fn(Service, MethodName, Parameter).await,
		"window.applyTextEdits" => ApplyTextEdits::Fn(Service, Parameter).await,
		"window.showMessage" => WindowShowMessage::Fn(Service, Parameter).await,
		"registerCommand" => crate::Vine::Server::Notification::RegisterCommand::Fn(Service, Parameter).await,
		"unregisterCommand" => UnregisterCommand::Fn(Service, Parameter).await,
		"unregister_authentication_provider" => UnregisterAuthenticationProvider::Fn(Service, Parameter).await,
		"unregister_debug_adapter" => UnregisterDebugAdapter::Fn(Service, Parameter).await,
		"unregister_debug_configuration_provider" => UnregisterDebugConfigurationProvider::Fn(Service, Parameter).await,
		"unregister_file_system_provider" => UnregisterFileSystemProvider::Fn(Service, Parameter).await,
		"unregister_scm_provider" => UnregisterScmProvider::Fn(Service, Parameter).await,
		"unregister_task_provider" => UnregisterTaskProvider::Fn(Service, Parameter).await,
		"unregister_external_uri_opener" => UnregisterExternalUriOpener::Fn(Service, Parameter).await,
		"unregister_remote_authority_resolver" => UnregisterRemoteAuthorityResolver::Fn(Service, Parameter).await,
		"unregister_uri_handler" => UnregisterUriHandler::Fn(Service, Parameter).await,
		"update_scm_group" => UpdateScmGroup::Fn(Service, Parameter).await,
		"languages.setDocumentLanguage" => LanguagesSetDocumentLanguage::Fn(Service, Parameter).await,
		"disposeStatusBarItem" => DisposeStatusBarItem::Fn(Service, Parameter).await,
		"output.create" | "outputChannel.create" => OutputChannelCreate::Fn(Service, Parameter).await,
		"output.append" | "outputChannel.append" => OutputChannelAppend::Fn(Service, Parameter).await,
		"output.appendLine" | "outputChannel.appendLine" => OutputAppendLine::Fn(Service, Parameter).await,
		"output.clear" | "outputChannel.clear" => OutputChannelClear::Fn(Service, Parameter).await,
		"outputChannel.show" => OutputChannelShow::Fn(Service, Parameter).await,
		"outputChannel.hide" => OutputChannelHide::Fn(Service, Parameter).await,
		"outputChannel.dispose" => OutputChannelDispose::Fn(Service, Parameter).await,
		"webview.postMessage" => WebviewPostMessage::Fn(Service, Parameter).await,
		"webview.dispose" => WebviewDispose::Fn(Service, Parameter).await,
		m if m.starts_with("webview.") => WebviewLifecycle::Fn(Service, MethodName, Parameter).await,
		m if m.starts_with("terminal.") => TerminalLifecycle::Fn(Service, MethodName, Parameter).await,
		m if m.starts_with("debug.") => DebugLifecycle::Fn(Service, MethodName, Parameter).await,
		m if m.starts_with("statusBar.") => DisposeStatusBarItem::Fn(Service, Parameter).await,
		m if m.starts_with("openExternal") => OpenExternal::Fn(Service, Parameter).await,
		_ => {},
	}
}
