
// Defines the function for sending a request-response gRPC call from Cocoon to Mountain.

import * as grpc from "@grpc/grpc-js";

import type {
	GenericRequest as GrpcGenericRequestPb,
	GenericResponse as GrpcGenericResponsePb,
	MountainServiceClient,
} from "../Generated/VineGrpcPb";
import {
	JsValueToProtoValue,
	ProtoValueToJsValue,
} from "../Util/ProtoValueConverter";
import { GetClientInstance } from "./Initialize";

const DEFAULT_REQUEST_TIMEOUT_MILLISECONDS = 30000;

/**
 * Sends a request to the Mountain gRPC service and awaits a response.
 * @param CocoonRequestId A unique identifier for this request, generated by the caller.
 * @param Method The name of the RPC method to invoke on the Mountain side.
 * @param Parameters The parameters for the RPC method.
 * @param TimeoutMilliseconds The timeout for the call in milliseconds.
 * @returns A promise that resolves with the result from Mountain or rejects with an error.
 */
export const SendRequestToMountain = async (
	CocoonRequestId: number,
	Method: string,
	Parameters: any,
	TimeoutMilliseconds?: number,
): Promise<any> => {
	const TimeoutValue =
		TimeoutMilliseconds || DEFAULT_REQUEST_TIMEOUT_MILLISECONDS;
	console.debug(
		`[GrpcClient SendRequest] >> To Mountain: CocoonReqID=${CocoonRequestId}, Method='${Method}', Timeout=${TimeoutValue}`,
	);
	if (console.trace && Parameters !== undefined) {
		console.trace(
			`[GrpcClient SendRequest] Params for ${Method}:`,
			Parameters,
		);
	}

	let MountainServiceClientInstance: MountainServiceClient;
	try {
		MountainServiceClientInstance = GetClientInstance().getRawClient();
	} catch (ClientError: any) {
		console.error(
			`[GrpcClient SendRequest] Failed to get gRPC client for ReqID=${CocoonRequestId}, Method='${Method}': ${ClientError.message}`,
		);
		throw ClientError;
	}

	const ProtoParameters = JsValueToProtoValue(Parameters);
	if (
		Parameters !== undefined &&
		ProtoParameters === undefined &&
		Parameters !== null
	) {
		const SerializationError = new Error(
			`Failed to serialize parameters for gRPC request method '${Method}'. Check console for details.`,
		);
		console.error(
			`[GrpcClient SendRequest] ${SerializationError.message}`,
			Parameters,
		);
		throw SerializationError;
	}

	const GrpcRequestPayload: GrpcGenericRequestPb = {
		request_id: CocoonRequestId,
		method: Method,
		params: ProtoParameters,
	} as GrpcGenericRequestPb; // Type assertion might be needed depending on generated types

	const CallOptions: Partial<grpc.CallOptions> = {
		deadline: Date.now() + TimeoutValue,
	};
	const Metadata = new grpc.Metadata();

	try {
		const GrpcResponse =
			await MountainServiceClientInstance.processCocoonRequest(
				GrpcRequestPayload,
				Metadata,
				CallOptions,
			);

		if (GrpcResponse.getError()) {
			const ApplicationErrorPb = GrpcResponse.getError()!;
			console.warn(
				`[GrpcClient SendRequest] Mountain returned application error for ReqID=${CocoonRequestId}, Method='${Method}': Code=${ApplicationErrorPb.getCode()}, Msg='${ApplicationErrorPb.getMessage()}'`,
			);
			const ApplicationError = new Error(
				ApplicationErrorPb.getMessage(),
			) as any;
			ApplicationError.code = ApplicationErrorPb.getCode();
			ApplicationError.data = ProtoValueToJsValue(
				ApplicationErrorPb.getData(),
			);
			ApplicationError.name = "MountainApplicationError";
			throw ApplicationError;
		}

		const ResultAsJs = ProtoValueToJsValue(GrpcResponse.getResult());
		console.debug(
			`[GrpcClient SendRequest] << Response for ReqID=${CocoonRequestId}, Method='${Method}' received successfully.`,
		);
		if (console.trace && ResultAsJs !== null) {
			console.trace(
				`[GrpcClient SendRequest] Response Result for ${Method}:`,
				ResultAsJs,
			);
		}
		return ResultAsJs;
	} catch (Error: any) {
		// This will catch both gRPC transport errors and application errors thrown above.
		console.error(
			`[GrpcClient SendRequest] Error during request (ReqID=${CocoonRequestId}, Method='${Method}'):`,
			Error,
		);
		const RefinedError =
			Error.name === "MountainApplicationError"
				? Error
				: (new Error(
						`gRPC request to Mountain method '${Method}' failed: ${Error.details || Error.message || String(Error)}`,
					) as any);

		if (!RefinedError.code) {
			RefinedError.code =
				Error.code ||
				(Error.details === "Deadline Exceeded"
					? grpc.status.DEADLINE_EXCEEDED
					: grpc.status.UNKNOWN);
		}
		if (!RefinedError.name) RefinedError.name = "MountainGrpcError";

		throw RefinedError;
	}
};
