//! # UIRequest Module (Track)
//!
//! Contains the UI request resolution functionality for the Track module.

// Use pub mod to ensure Tauri command helpers are accessible
pub mod ResolveUIRequest;

// Re-export for backward compatibility
pub use ResolveUIRequest::ResolveUIRequest;

// Also re-export the Tauri command helper that's generated by the macro
pub use ResolveUIRequest::__cmd__ResolveUIRequest;
