//! # ProviderRegistrationDTO
//!
//! Defines the Data Transfer Object for storing the state of a registered
//! language feature provider.

#![allow(non_snake_case, non_camel_case_types)]

use Common::LanguageFeature::DTO::ProviderType::ProviderType;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Stores the registration details for a single language feature provider
/// contributed by an extension. This is stored in `ApplicationState` to track
/// all active providers.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "PascalCase")]
pub struct ProviderRegistrationDTO {
	/// A unique handle for this registration, generated by Mountain.
	pub Handle:u32,

	/// The type of feature this provider implements.
	pub ProviderType:ProviderType,

	/// The document selector (serialized as a `Value`) that determines which
	/// documents this provider applies to.
	pub Selector:Value,

	/// The identifier of the sidecar process that hosts this provider's logic.
	pub SidecarIdentifier:String,

	/// The identifier of the extension that contributed this provider.
	pub ExtensionIdentifier:Value,

	/// Optional, feature-specific options for this provider.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Options:Option<Value /* ProviderOptionsDTO */>,
}
