pub mod Create;
pub mod CreateWithAir;
pub mod SetAirClient;
pub mod IsAirAvailable;
pub mod IsAirAvailable;

use std::sync::Arc;
use AirLibrary::Vine::Generated::air::air_service_client::AirServiceClient;
use CommonLibrary::{
	Command::CommandExecutor::CommandExecutor,
	Configuration::{ConfigurationInspector::ConfigurationInspector, ConfigurationProvider::ConfigurationProvider},
	CustomEditor::CustomEditorProvider::CustomEditorProvider,
	Debug::DebugService::DebugService,
	Diagnostic::DiagnosticManager::DiagnosticManager,
	Document::DocumentProvider::DocumentProvider,
	Environment::{Environment::Environment, Requires::Requires},
	Error::CommonError::CommonError,
	ExtensionManagement::ExtensionManagementService::ExtensionManagementService,
	FileSystem::{
		FileSystemReader::FileSystemReader,
		FileSystemWriter::FileSystemWriter,
		FileWatcherProvider::FileWatcherProvider,
	},
	IPC::IPCProvider::IPCProvider,
	Keybinding::KeybindingProvider::KeybindingProvider,
	LanguageFeature::LanguageFeatureProviderRegistry::LanguageFeatureProviderRegistry,
	Output::OutputChannelManager::OutputChannelManager,
	Search::SearchProvider::SearchProvider,
	Secret::SecretProvider::SecretProvider,
	SourceControlManagement::SourceControlManagementProvider::SourceControlManagementProvider,
	StatusBar::StatusBarProvider::StatusBarProvider,
	Storage::StorageProvider::StorageProvider,
	Synchronization::SynchronizationProvider::SynchronizationProvider,
	Terminal::TerminalProvider::TerminalProvider,
	Testing::TestController::TestController,
	TreeView::TreeViewProvider::TreeViewProvider,
	UserInterface::UserInterfaceProvider::UserInterfaceProvider,
	Webview::WebviewProvider::WebviewProvider,
	Workspace::{WorkspaceEditApplier::WorkspaceEditApplier, WorkspaceProvider::WorkspaceProvider},
};
use async_trait::async_trait;
use serde_json::Value;
use tauri::{AppHandle, Wry};
use crate::{
	ApplicationState::{
		DTO::ExtensionDescriptionStateDTO::ExtensionDescriptionStateDTO,
		Struct::ApplicationState::ApplicationState,
	},
	dev_log,
};
use crate::impl_provider;

/// The concrete `Environment` for the Mountain application.
/// Primary dependency injection container for the Mountain code editor.
/// Holds thread-safe references to application state, the async runtime,
/// and the optional Air service client. Provider trait implementations
/// are generated by `impl_provider!` to enable `Requires<T>` lookups.
#[derive(Clone)]
pub struct Struct {
	/// Tauri application handle for window and event management.
	pub ApplicationHandle:AppHandle<Wry>,

	/// Thread-safe shared application state machine.
	pub ApplicationState:Arc<ApplicationState>,

	/// Optional Air gRPC client for cloud-based services.
	///
	/// When provided (`AirIntegration` feature enabled), providers such as
	/// `SecretProvider` and `UpdateService` can delegate to the Air service.
	#[cfg(feature = "AirIntegration")]
	pub AirClient:Option<AirServiceClient<tonic::transport::Channel>>,
}
