//! # Webview Module (Track)
//!
//! Contains the webview message forwarding functionality for the Track module.

// Use pub mod to ensure Tauri command helpers are accessible
pub mod MountainWebviewPostMessageFromGuest;

// Re-export for backward compatibility
pub use MountainWebviewPostMessageFromGuest::MountainWebviewPostMessageFromGuest;
// Also re-export the Tauri command helper that's generated by the macro
pub use MountainWebviewPostMessageFromGuest::__cmd__MountainWebviewPostMessageFromGuest;
