

// File: EsmInterceptor/Dynamic/DynamicTemplate.ts
// Contains the template string for the dynamically generated ES module
// that provides the `vscode` API to extensions.

/**
 * This is the raw text content of the JavaScript module that will be served
 * for `import "vscode"` requests. It uses placeholders that are replaced at runtime.
 *
 * - `ESBUILD_REPLACED_GLOBAL_API_FUNCTION_NAME`: This placeholder is replaced by the esbuild
 *   `define` option with the actual name of the global function that retrieves the API instance.
 *   This prevents the function name from being minified or tree-shaken.
 * - `__RUNTIME_API_KEY__`: This placeholder is replaced at runtime with the unique API key
 *   generated for the specific extension's `vscode` API instance.
 * - `__RUNTIME_EXPORT_STATEMENTS__`: This placeholder is replaced at runtime with a
 *   dynamically generated list of `export const ...` statements for every property on the
 *   `vscode` API object.
 */
const DynamicModuleTemplateContent: &str = r#"
// This module is dynamically generated by Cocoon's ESM interceptor.

// Retrieve the vscode API instance from the global scope using the unique key for this extension context.
const __apiInstance =
    globalThis[ESBUILD_REPLACED_GLOBAL_API_FUNCTION_NAME](__RUNTIME_API_KEY__);

// Error out if the API instance could not be retrieved. This is a critical failure.
if (!__apiInstance) {
    throw new Error(
        `Cocoon Critical Error: Failed to retrieve vscode API instance for ESM module. ` +
        `API Key: "${__RUNTIME_API_KEY__}". ` +
        `Global Function: '${ESBUILD_REPLACED_GLOBAL_API_FUNCTION_NAME}'. ` +
        `This indicates a failure in the API factory or caching mechanism.`
    );
}

// Dynamically generated export statements for every property on the vscode API object.
// This ensures that `import { window, commands } from 'vscode'` works as expected.
__RUNTIME_EXPORT_STATEMENTS__;

// Export the entire API object as the default export, for `import vscode from 'vscode'`.
export default __apiInstance;
"#;

// This would be a `pub const` in Rust.
export default DynamicModuleTemplateContent;
