// @module ProviderRegistrationDTO
// @description Defines the Data Transfer Object for a registered language
// feature provider.

#![allow(non_snake_case, non_camel_case_types)]

use Common::language_feature::DTO::{ProviderOptionsDTO, ProviderType};
use serde::{Deserialize, Serialize};
use serde_json::Value;

// Stores the registration details for a single language feature provider from
// an extension.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "PascalCase")]
pub struct ProviderRegistrationDTO {
	// A unique handle for this registration, generated by Mountain.
	pub Handle:u32,
	// The type of feature this provider implements.
	pub ProviderType:ProviderType,
	// The document selector (serialized as a `Value`) that determines which
	// documents this provider applies to.
	pub Selector:Value,
	// The identifier of the sidecar process that hosts this provider.
	pub SidecarIdentifier:String,
	// The identifier of the extension that contributed this provider.
	pub ExtensionIdentifier:Value,
	// Optional, feature-specific options for this provider.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub Options:Option<ProviderOptionsDTO>,
}
