//! # FrontendCommand Module (Track)
//!
//! Contains the frontend command dispatch functionality for the Track module.

// Use pub mod to ensure Tauri command helpers are accessible
pub mod DispatchFrontendCommand;

// Re-export for backward compatibility
pub use DispatchFrontendCommand::DispatchFrontendCommand;
// Also re-export the Tauri command helper that's generated by the macro
pub use DispatchFrontendCommand::__cmd__DispatchFrontendCommand;
